// import { Poppins } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";
// <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'></link>


// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: '--body-font',
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={Oswald.className}>
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }


import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}