// import { Poppins } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";

// const poppins = Poppins({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={poppins.className}>{children}</body>
//     </html>
//   );
// }
import Head from "next/head";
import { Poppins } from "next/font";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Poppins />
        {children}
      </body>
    </>
  );
}
